services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mindwork_sqlserver
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Mindwork2024!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mindwork_net

networks:
  mindwork_net:

volumes:
  sqlserver_data:
